### ISSUE TITLE
fix_filename missing

### ISSUE THREAD

**Issue by eithe** [odinuge/NRK-TV-Downloader#4]
Hi, where should the fix_filename function come from? Getting:

     ./nrk-dl.sh: line 324: fix_filename: command not found

It works without it, just wondering .. :) Thanks for creating it!

**Comment by odinuge** [comment]
Thanks for using my work!

It's been a long time since i did something with it, so it isn't quite up to date at the moment. I have fixed your issue in commit 9205c7a9837544a0bc738c6528569a91da89a972, together with some other minor fixes. I plan to make the script fully up to date (to NRK's new design) in the next few weeks.

**Comment by eithe** [comment]
Thanks! Btw, in case you didn't know you could avoid some scraping if you rewrote to use the NRK TV api: http://v8.psapi.nrk.no/Help

We use it in our Plex NRK channel if you need an example (link to the repo through my profile).

**Comment by odinuge** [comment]
What? The new API looks awesome! i'll definitely look at your examples.

I think i will have some spare time this weekend, so i'll try to rewrite the code using the new V8-API.
