### ISSUE TITLE
Can't download - correct information received - invalid argument

### ISSUE THREAD

**Issue by theodorjs** [odinuge/nrk-tv-downloader#42]
![skjermbilde 2019-02-08 kl 16 20 25](https://user-images.githubusercontent.com/44986321/52487619-5026a000-2bbe-11e9-9a48-fbb4ecab689c.png)

Any suggestions?

**Comment by odinuge** [comment]
Hi!

Looks like your default awk isn't gawk (required by this script), and that results in a crash. Maybe you use a mac? Some linux distros also ships with non-gawk defaults, and switches the `awk` command to gawk when it is installed. Since the script doesn't say `Error: Required program could not be found: gawk`, you should have all the required utils for it to run.

I switched the last `awk` commands to `gawk` in https://github.com/odinuge/nrk-tv-downloader/pull/43, so it should work in the current master (just run `git pull`). :smile:

**Comment by theodorjs** [comment]
Hi! 
Yes, I'm using a mac. I think I installed gawk through homebrew before I tried running the shell. Thank you for the update! I will try it again,

**Comment by theodorjs** [comment]
![skjermbilde 2019-02-09 kl 14 32 43](https://user-images.githubusercontent.com/44986321/52521455-aad00280-2c77-11e9-9ebe-4ba681421f65.png)
I ran "git pull" but I'm still encountering the same problem.

**Comment by odinuge** [comment]
Hi @theodorjs!

After some googleing it looks like this is a "problem" with avconv. I don't have a mac available, but the stuff in #45 might fix the problem; feel free to try that. You can also try to upgrade avconv, as someone said that upgrading fixed a similar problem. :smile:
